import Fluent

struct CreateMuniAppRegistryMigration: AsyncMigration {
    func prepare(on database: Database) async throws {
        try await database.schema(MuniAppRow.schema)
            .field("id", .int, .identifier(auto: true))
            .field("app_id", .string, .required)
            .field("display_name", .string, .required)
            .field("mission", .string, .required)
            .field("repository_path", .string)
            .field("executable", .string, .required)
            .field("executable_path", .string)
            .field("version", .string, .required)
            .field("integration_status", .string, .required)
            .field("capabilities_json", .string, .required)
            .field("default_action", .string, .required)
            .field("default_parameters_json", .string, .required)
            .field("supports_dry_run", .bool, .required)
            .field("destructive_requires_confirmation", .bool, .required)
            .field("confirmation_parameter", .string)
            .field("enabled", .bool, .required)
            .field("created_at", .datetime, .required)
            .field("updated_at", .datetime, .required)
            .unique(on: "app_id")
            .create()

        try await database.schema(MuniAppActionRow.schema)
            .field("id", .int, .identifier(auto: true))
            .field("app_id", .string, .required)
            .field("action_key", .string, .required)
            .field("action_label", .string, .required)
            .field("is_primary", .bool, .required)
            .field("created_at", .datetime, .required)
            .field("updated_at", .datetime, .required)
            .unique(on: "app_id", "action_key")
            .create()

        try await database.schema(RunProfileRow.schema)
            .field("id", .int, .identifier(auto: true))
            .field("app_id", .string, .required)
            .field("profile_key", .string, .required)
            .field("display_name", .string, .required)
            .field("action_key", .string, .required)
            .field("parameters_json", .string, .required)
            .field("allow_destructive", .bool, .required)
            .field("expert_only", .bool, .required)
            .field("created_at", .datetime, .required)
            .field("updated_at", .datetime, .required)
            .unique(on: "app_id", "profile_key")
            .create()

        try await database.schema(RunHistoryRow.schema)
            .field("id", .int, .identifier(auto: true))
            .field("execution_id", .string, .required)
            .field("request_id", .string, .required)
            .field("app_id", .string, .required)
            .field("action", .string, .required)
            .field("status", .string, .required)
            .field("summary", .string)
            .field("command_json", .string, .required)
            .field("request_file", .string, .required)
            .field("result_file", .string, .required)
            .field("exit_code", .int)
            .field("started_at", .datetime, .required)
            .field("finished_at", .datetime, .required)
            .field("dry_run", .bool)
            .field("error_codes_json", .string, .required)
            .field("created_at", .datetime, .required)
            .unique(on: "execution_id")
            .create()

        try await database.schema(RunDiagnosticRow.schema)
            .field("id", .int, .identifier(auto: true))
            .field("execution_id", .string, .required)
            .field("diagnostic_id", .string, .required)
            .field("severity", .string, .required)
            .field("label", .string, .required)
            .field("cta", .string)
            .field("source", .string, .required)
            .field("details", .string)
            .field("created_at", .datetime, .required)
            .create()
    }

    func revert(on database: Database) async throws {
        try await database.schema(RunDiagnosticRow.schema).delete()
        try await database.schema(RunHistoryRow.schema).delete()
        try await database.schema(RunProfileRow.schema).delete()
        try await database.schema(MuniAppActionRow.schema).delete()
        try await database.schema(MuniAppRow.schema).delete()
    }
}
